### PR TITLE
[WIP] Implement Mango Query

### PR DESCRIPTION
**Pull request by popojargo**

### CODE REVIEW

**Comment by popojargo** [comment]
- [ ] Add new functions documentations
- [ ] Add code style page
- [ ] Add changelist
- [ ] Validate documentation base on changelit

**Comment by popojargo** [comment]
@andreyvk Do you have any suggestions?

**Comment by andreyvk** [comment]
@popojargo hi,

I think implementation should rather be straightforward. I've looked at the code before. That time it did, it seemed to be easy to add a couple of methods on top of the existing infrastructure like `$client->setQueryParameters($queryOpts)->find($searchOpts)`, for instance.  When is the next release due?

**Comment by popojargo** [comment]
@andreyvk  
I'm not sure to understand all of what you've said. You prefer to have more chainable parameters instead of the functions parameters? Or it's ok like this?

Adding more chainable parameters could be an option but I don't want the people to be confused with Query Parameters and other chainable parameters. 


I will release once this branch is merged and tested by few users.

**Comment by andreyvk** [comment]
@popojargo sorry for late reply and misunderstanding. What I mean is that I'd prefer to keep it consistent with how library worked previously. For instance, you could chain all query parameters using `setQueryOptions` and then make a call to `getView` or you could chain them one by one just like shown in the example `$view = $client->limit(100)->getView('orders', 'by-date');`. It looks to me that implementation of [`_find`](http://docs.couchdb.org/en/2.0.0/api/database/find.html) is not so different and could be easily extended from existing infrastructure.

**Comment by popojargo** [comment]
$client->limit($n)->skip($s)->sort([sort array...])->fields([fields])->find($selector,$indexName = null)

I think this is the best I could do. I don't want to put the $selector as another chainable parameters since we need to have one to do the find query. Also, having only 2 parameters for the find function would be way cleaner. Do we agree on this?

**Comment by andreyvk** [comment]
I think this is cool )) cant wait till this comes out!

**Comment by popojargo** [comment]
Ok so I will refactor the find paramters as chainable properties then I will merge this PR this week.

**Comment by popojargo** [comment]
Todo : CreateIndex should take an object as option parameter. This should contain most of the optional fields. Then, I will merge this PR.

**Pull request merged**
