### PR TITLE
Add method to set a list of user role

### PR DESCRIPTION
**Pull request by kl3sk**
Instead of removing then adding each roles for a user, that result in a many revision update.
Erase all roles with a list of new roles

### CODE REVIEW

**Comment by popojargo** [comment]
Could you also add a test case for this new function? Adding the function to the documentation would also be appreciated but I can do this part if you don't

**Comment by kl3sk** [comment]
Could you please do this ?
I'll check how you do (because i'm not sure on how to achieve this) and i'll add this for the next PR ;)

thx

**Comment by popojargo** [comment]
Ok I'll handle it. I will fork your branch and make a PR on your PR  tonigh

**Comment by popojargo** [comment]
@kl3sk  Please accept the pull request that I have made on your patch so I can accept this PR

**Pull request merged**
